### ISSUE TITLE
大佬，反馈几个问题。

### ISSUE THREAD

**Issue by superzjg** [SWRT-dev/softcenterarmng#20]
更新最新版固件：388_TY6201_BCM_B5.2.0-g64cbd15 软件中心1.4.6
1、许多插件网页在edge、Safari浏览器显示异常，比如frpc、frps、speedtest、shellinabox，表现为上部和左部内容不显示，插件页面含输入框的内容不显示（比如frpc、frps都含有输入框），进程运行状态不显示等，影响使用。
无意中发现他们的asp中都有 <script type="text/javascript" src="/calendar/jquery-ui.js"></script> 这一行，删掉，就能显示正常了。
2、zerotier更新于2022年12月的新版，不能运行起来。
3、shellinabox经常抽风无法运行，当我运行了frpc、filebrowser等插件后，webshell经常无法打开。报日志：syslog: Check failed at shellinabox/launcher.c:721 in closeAllFds(): nullFd > 2
4、有关新版固件：B5.2.0-g64cbd15 ，内置的DDNS服务器：www.asus.com.cn，会每分钟更新并写入系统日志，导致日志内容很多（日志文件/jffs/syslog.log存在闪存中而不是RAM中，担心写入寿命），换用服务器：www.asus.com则不会频繁出日志。

**Comment by paldier** [comment]
已更新
