### ISSUE TITLE
开启koolproxy后进https网页显示隐私错误

### ISSUE THREAD

**Issue by 1779587460** [SWRT-dev/softcenterarmng#21]
388_TY6201_BCM_B5.2.0-g64cbd15
证书装过了，证书也没显示过期
![image_2023-01-23_13-54-37](https://user-images.githubusercontent.com/57093174/214005363-9639fa1f-3f43-4f58-9655-265a36cdfbcf.png)

**Comment by paldier** [comment]
hsts就是https堵上允许中间人攻击漏洞的措施，既然不再允许中间人攻击，自然就不能再去广告
